# deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: churn-app-deployment
spec:
  replicas: 3
  selector:
    matchLabels:
      app: churn-app
  template:
    metadata:
      labels:
        app: churn-app
    spec:
      containers:
      - name: churn-app
        image: churn-app:latest
        ports:
        - containerPort: 5000