# deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: creditability-app-deployment
spec:
  replicas: 3
  selector:
    matchLabels:
      app: creditability-app
  template:
    metadata:
      labels:
        app: creditability-app
    spec:
      containers:
      - name: creditability-app
        image: creditability-app:1.0.0
        ports:
        - containerPort: 5000