# service.yaml
apiVersion: v1
kind: Service
metadata:
  name: creditability-app-service
spec:
  selector:
    app: creditability-app
  ports:
    - protocol: TCP
      port: 80
      targetPort: 5000
      nodePort: 30007
  type: NodePort