# service.yaml
apiVersion: v1
kind: Service
metadata:
  name: churn-app-service
spec:
  selector:
    app: churn-app
  ports:
    - protocol: TCP
      port: 80
      targetPort: 5000
  type: LoadBalancer